///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class VideoSourceListItem {
  /*
{
  "vod_id": 89394,
  "type_id": 6,
  "type_id_1": 1,
  "group_id": 0,
  "vod_name": "魔法坏女巫2",
  "vod_sub": "魔法坏女巫(下) / 魔法坏女巫：第二章(港) / 魔法坏女巫：第二部 / Wicked: Deuxième Partie / Wicked: Part Two‎",
  "vod_en": "mofahuainvwu2",
  "vod_status": 1,
  "vod_letter": "M",
  "vod_color": "",
  "vod_tag": "",
  "vod_class": "动作,爱情,歌舞,奇幻,冒险",
  "vod_pic": "https://img.ffzy888.com/upload/vod/20251119-1/f76c3bcd9e4834d48a80296c78c27d20.jpg",
  "vod_pic_thumb": "",
  "vod_pic_slide": "",
  "vod_pic_screenshot": "",
  "vod_actor": "辛西娅·埃里沃,爱莉安娜·格兰德,杰夫·高布伦,杨紫琼,乔纳森·贝利,伊桑·斯莱特,玛丽莎·博德,彼特·丁拉基,科尔曼·多明戈,亚当·詹姆斯,艾米丽·蒂尔尼,艾琳·巴特尔,迈克尔·瓜内拉,莎拉-杰恩·里德尔,雅雅·哈姆扎,瑞安·曼,乔尔·斯特恩,利里奥·博阿滕,莉兹·艾森,里卡多·卢德罗·苏萨,卡勒姆·鲍耶",
  "vod_director": "朱浩伟",
  "vod_writer": "莱曼·弗兰克·鲍姆,温妮·霍尔兹曼,格雷戈里·马奎尔",
  "vod_behind": "",
  "vod_blurb": "　　自从艾芙芭（辛西娅·埃里沃 饰）与格琳达（爱莉安娜·格兰德 饰）分道扬镳、形同陌路之后，各自承受她们做出的抉择所带来的后果。　　被冠上“西方坏女巫”恶名的艾芙芭遭到放逐后，隐居在奥兹国树林深处，但",
  "vod_remarks": "HD中字",
  "vod_pubdate": "2025-11-21",
  "vod_total": 0,
  "vod_serial": "",
  "vod_tv": "",
  "vod_weekday": "",
  "vod_area": "美国",
  "vod_lang": "英语",
  "vod_year": "2025",
  "vod_version": "",
  "vod_state": "正片",
  "vod_author": "",
  "vod_jumpurl": "",
  "vod_tpl": "",
  "vod_tpl_play": "",
  "vod_tpl_down": "",
  "vod_isend": 0,
  "vod_lock": 0,
  "vod_level": 0,
  "vod_copyright": 0,
  "vod_points": 0,
  "vod_points_play": 0,
  "vod_points_down": 0,
  "vod_hits": 0,
  "vod_hits_day": 0,
  "vod_hits_week": 0,
  "vod_hits_month": 0,
  "vod_duration": "",
  "vod_up": 0,
  "vod_down": 0,
  "vod_score": "0.0",
  "vod_score_all": 0,
  "vod_score_num": 0,
  "vod_time": "2025-12-30 14:59:31",
  "vod_time_add": 1763482690,
  "vod_time_hits": 0,
  "vod_time_make": 0,
  "vod_trysee": 0,
  "vod_douban_id": 36175206,
  "vod_douban_score": "0.0",
  "vod_reurl": "",
  "vod_rel_vod": "",
  "vod_rel_art": "",
  "vod_pwd": "",
  "vod_pwd_url": "",
  "vod_pwd_play": "",
  "vod_pwd_play_url": "",
  "vod_pwd_down": "",
  "vod_pwd_down_url": "",
  "vod_content": "<p>　　自从艾芙芭（辛西娅·埃里沃 饰）与格琳达（爱莉安娜·格兰德 饰）分道扬镳、形同陌路之后，各自承受她们做出的抉择所带来的后果。<br/>　　被冠上“西方坏女巫”恶名的艾芙芭遭到放逐后，隐居在奥兹国树林深处，但是却仍然为被噤声的动物争取自由而奋斗，并且迫切地想要揭露她所知道关于奥兹国大巫师（杰夫· 高布伦 饰）的真相。<br/>　　与此同时，格琳达已经成为奥兹国光鲜亮丽的良善象征，她住在翡翠城皇宫中， 享受她的响亮名声和超高人气所带来的明星光环与特权。在莫里贝尔夫人（杨紫琼 饰）的安排下，格琳达成为奥兹国人民眼中充满粉红泡泡的安抚力量，并且让他们相信奥兹国在大巫师的统治之下一切都很好。<br/>　　当格琳达的明星光环越来越闪亮，她也准备和费耶罗王子（乔纳森·贝利 饰）举行一场盛大的婚礼，但是她却一直受到她和艾芙芭分开后的阴影所纠缠。她试图促成艾芙芭与大巫师之间的和解，然而她所有的努力都以失败告终，使得艾芙芭和格琳达的关系越来越疏远。她们的关系决裂所造成的影响，将彻底改变博克（伊森·斯莱特 饰）与费耶罗的命运，也将威胁到艾芙芭的妹妹涅莎萝丝（玛丽莎·博德 饰）的安危，而一名来自堪萨斯州的少女也将闯入奥兹国，彻底翻转他们的世界。<br/>　　当一群愤怒的民众揭竿而起，打算对抗西方坏女巫，格琳达和艾芙芭就必须最后一次携手合作。当她们的友情成为改变她们未来的关键，她们就必须以真心诚意和无比的同理心真正了解彼此，并且改变自己，也让整个奥兹国变得更美好。</p>",
  "vod_play_from": "feifan$$$ffm3u8",
  "vod_play_server": "no$$$no",
  "vod_play_note": "$$$",
  "vod_play_url": "HD中字$https://vip.ffzy-online.com/share/7bda1a1c4b780f467d4ece9a47eb5c1b$$$HD中字$https://vip.ffzy-online.com/20251230/57466_7bda1a1c/index.m3u8",
  "vod_down_from": "",
  "vod_down_server": "",
  "vod_down_note": "",
  "vod_down_url": "",
  "vod_plot": 0,
  "vod_plot_name": "",
  "vod_plot_detail": "",
  "type_name": "动作片"
} 
*/

  int? vodId;
  int? typeId;
  int? typeId_1;
  int? groupId;
  String? vodName;
  String? vodSub;
  String? vodEn;
  int? vodStatus;
  String? vodLetter;
  String? vodColor;
  String? vodTag;
  String? vodClass;
  String? vodPic;
  String? vodPicThumb;
  String? vodPicSlide;
  String? vodPicScreenshot;
  String? vodActor;
  String? vodDirector;
  String? vodWriter;
  String? vodBehind;
  String? vodBlurb;
  String? vodRemarks;
  String? vodPubdate;
  int? vodTotal;
  String? vodSerial;
  String? vodTv;
  String? vodWeekday;
  String? vodArea;
  String? vodLang;
  String? vodYear;
  String? vodVersion;
  String? vodState;
  String? vodAuthor;
  String? vodJumpurl;
  String? vodTpl;
  String? vodTplPlay;
  String? vodTplDown;
  int? vodIsend;
  int? vodLock;
  int? vodLevel;
  int? vodCopyright;
  int? vodPoints;
  int? vodPointsPlay;
  int? vodPointsDown;
  int? vodHits;
  int? vodHitsDay;
  int? vodHitsWeek;
  int? vodHitsMonth;
  String? vodDuration;
  int? vodUp;
  int? vodDown;
  String? vodScore;
  int? vodScoreAll;
  int? vodScoreNum;
  String? vodTime;
  int? vodTimeAdd;
  int? vodTimeHits;
  int? vodTimeMake;
  int? vodTrysee;
  int? vodDoubanId;
  String? vodDoubanScore;
  String? vodReurl;
  String? vodRelVod;
  String? vodRelArt;
  String? vodPwd;
  String? vodPwdUrl;
  String? vodPwdPlay;
  String? vodPwdPlayUrl;
  String? vodPwdDown;
  String? vodPwdDownUrl;
  String? vodContent;
  String? vodPlayFrom;
  String? vodPlayServer;
  String? vodPlayNote;
  String? vodPlayUrl;
  String? vodDownFrom;
  String? vodDownServer;
  String? vodDownNote;
  String? vodDownUrl;
  int? vodPlot;
  String? vodPlotName;
  String? vodPlotDetail;
  String? typeName;

  VideoSourceListItem({
    this.vodId,
    this.typeId,
    this.typeId_1,
    this.groupId,
    this.vodName,
    this.vodSub,
    this.vodEn,
    this.vodStatus,
    this.vodLetter,
    this.vodColor,
    this.vodTag,
    this.vodClass,
    this.vodPic,
    this.vodPicThumb,
    this.vodPicSlide,
    this.vodPicScreenshot,
    this.vodActor,
    this.vodDirector,
    this.vodWriter,
    this.vodBehind,
    this.vodBlurb,
    this.vodRemarks,
    this.vodPubdate,
    this.vodTotal,
    this.vodSerial,
    this.vodTv,
    this.vodWeekday,
    this.vodArea,
    this.vodLang,
    this.vodYear,
    this.vodVersion,
    this.vodState,
    this.vodAuthor,
    this.vodJumpurl,
    this.vodTpl,
    this.vodTplPlay,
    this.vodTplDown,
    this.vodIsend,
    this.vodLock,
    this.vodLevel,
    this.vodCopyright,
    this.vodPoints,
    this.vodPointsPlay,
    this.vodPointsDown,
    this.vodHits,
    this.vodHitsDay,
    this.vodHitsWeek,
    this.vodHitsMonth,
    this.vodDuration,
    this.vodUp,
    this.vodDown,
    this.vodScore,
    this.vodScoreAll,
    this.vodScoreNum,
    this.vodTime,
    this.vodTimeAdd,
    this.vodTimeHits,
    this.vodTimeMake,
    this.vodTrysee,
    this.vodDoubanId,
    this.vodDoubanScore,
    this.vodReurl,
    this.vodRelVod,
    this.vodRelArt,
    this.vodPwd,
    this.vodPwdUrl,
    this.vodPwdPlay,
    this.vodPwdPlayUrl,
    this.vodPwdDown,
    this.vodPwdDownUrl,
    this.vodContent,
    this.vodPlayFrom,
    this.vodPlayServer,
    this.vodPlayNote,
    this.vodPlayUrl,
    this.vodDownFrom,
    this.vodDownServer,
    this.vodDownNote,
    this.vodDownUrl,
    this.vodPlot,
    this.vodPlotName,
    this.vodPlotDetail,
    this.typeName,
  });

  VideoSourceListItem.fromJson(Map<String, dynamic> json) {
    vodId = json['vod_id']?.toInt();
    typeId = json['type_id']?.toInt();
    typeId_1 = json['type_id_1']?.toInt();
    groupId = json['group_id']?.toInt();
    vodName = json['vod_name']?.toString();
    vodSub = json['vod_sub']?.toString();
    vodEn = json['vod_en']?.toString();
    vodStatus = json['vod_status']?.toInt();
    vodLetter = json['vod_letter']?.toString();
    vodColor = json['vod_color']?.toString();
    vodTag = json['vod_tag']?.toString();
    vodClass = json['vod_class']?.toString();
    vodPic = json['vod_pic']?.toString();
    vodPicThumb = json['vod_pic_thumb']?.toString();
    vodPicSlide = json['vod_pic_slide']?.toString();
    vodPicScreenshot = json['vod_pic_screenshot']?.toString();
    vodActor = json['vod_actor']?.toString();
    vodDirector = json['vod_director']?.toString();
    vodWriter = json['vod_writer']?.toString();
    vodBehind = json['vod_behind']?.toString();
    vodBlurb = json['vod_blurb']?.toString();
    vodRemarks = json['vod_remarks']?.toString();
    vodPubdate = json['vod_pubdate']?.toString();
    vodTotal = json['vod_total']?.toInt();
    vodSerial = json['vod_serial']?.toString();
    vodTv = json['vod_tv']?.toString();
    vodWeekday = json['vod_weekday']?.toString();
    vodArea = json['vod_area']?.toString();
    vodLang = json['vod_lang']?.toString();
    vodYear = json['vod_year']?.toString();
    vodVersion = json['vod_version']?.toString();
    vodState = json['vod_state']?.toString();
    vodAuthor = json['vod_author']?.toString();
    vodJumpurl = json['vod_jumpurl']?.toString();
    vodTpl = json['vod_tpl']?.toString();
    vodTplPlay = json['vod_tpl_play']?.toString();
    vodTplDown = json['vod_tpl_down']?.toString();
    vodIsend = json['vod_isend']?.toInt();
    vodLock = json['vod_lock']?.toInt();
    vodLevel = json['vod_level']?.toInt();
    vodCopyright = json['vod_copyright']?.toInt();
    vodPoints = json['vod_points']?.toInt();
    vodPointsPlay = json['vod_points_play']?.toInt();
    vodPointsDown = json['vod_points_down']?.toInt();
    vodHits = json['vod_hits']?.toInt();
    vodHitsDay = json['vod_hits_day']?.toInt();
    vodHitsWeek = json['vod_hits_week']?.toInt();
    vodHitsMonth = json['vod_hits_month']?.toInt();
    vodDuration = json['vod_duration']?.toString();
    vodUp = json['vod_up']?.toInt();
    vodDown = json['vod_down']?.toInt();
    vodScore = json['vod_score']?.toString();
    vodScoreAll = json['vod_score_all']?.toInt();
    vodScoreNum = json['vod_score_num']?.toInt();
    vodTime = json['vod_time']?.toString();
    vodTimeAdd = json['vod_time_add']?.toInt();
    vodTimeHits = json['vod_time_hits']?.toInt();
    vodTimeMake = json['vod_time_make']?.toInt();
    vodTrysee = json['vod_trysee']?.toInt();
    vodDoubanId = json['vod_douban_id']?.toInt();
    vodDoubanScore = json['vod_douban_score']?.toString();
    vodReurl = json['vod_reurl']?.toString();
    vodRelVod = json['vod_rel_vod']?.toString();
    vodRelArt = json['vod_rel_art']?.toString();
    vodPwd = json['vod_pwd']?.toString();
    vodPwdUrl = json['vod_pwd_url']?.toString();
    vodPwdPlay = json['vod_pwd_play']?.toString();
    vodPwdPlayUrl = json['vod_pwd_play_url']?.toString();
    vodPwdDown = json['vod_pwd_down']?.toString();
    vodPwdDownUrl = json['vod_pwd_down_url']?.toString();
    vodContent = json['vod_content']?.toString();
    vodPlayFrom = json['vod_play_from']?.toString();
    vodPlayServer = json['vod_play_server']?.toString();
    vodPlayNote = json['vod_play_note']?.toString();
    vodPlayUrl = json['vod_play_url']?.toString();
    vodDownFrom = json['vod_down_from']?.toString();
    vodDownServer = json['vod_down_server']?.toString();
    vodDownNote = json['vod_down_note']?.toString();
    vodDownUrl = json['vod_down_url']?.toString();
    vodPlot = json['vod_plot']?.toInt();
    vodPlotName = json['vod_plot_name']?.toString();
    vodPlotDetail = json['vod_plot_detail']?.toString();
    typeName = json['type_name']?.toString();
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['vod_id'] = vodId;
    data['type_id'] = typeId;
    data['type_id_1'] = typeId_1;
    data['group_id'] = groupId;
    data['vod_name'] = vodName;
    data['vod_sub'] = vodSub;
    data['vod_en'] = vodEn;
    data['vod_status'] = vodStatus;
    data['vod_letter'] = vodLetter;
    data['vod_color'] = vodColor;
    data['vod_tag'] = vodTag;
    data['vod_class'] = vodClass;
    data['vod_pic'] = vodPic;
    data['vod_pic_thumb'] = vodPicThumb;
    data['vod_pic_slide'] = vodPicSlide;
    data['vod_pic_screenshot'] = vodPicScreenshot;
    data['vod_actor'] = vodActor;
    data['vod_director'] = vodDirector;
    data['vod_writer'] = vodWriter;
    data['vod_behind'] = vodBehind;
    data['vod_blurb'] = vodBlurb;
    data['vod_remarks'] = vodRemarks;
    data['vod_pubdate'] = vodPubdate;
    data['vod_total'] = vodTotal;
    data['vod_serial'] = vodSerial;
    data['vod_tv'] = vodTv;
    data['vod_weekday'] = vodWeekday;
    data['vod_area'] = vodArea;
    data['vod_lang'] = vodLang;
    data['vod_year'] = vodYear;
    data['vod_version'] = vodVersion;
    data['vod_state'] = vodState;
    data['vod_author'] = vodAuthor;
    data['vod_jumpurl'] = vodJumpurl;
    data['vod_tpl'] = vodTpl;
    data['vod_tpl_play'] = vodTplPlay;
    data['vod_tpl_down'] = vodTplDown;
    data['vod_isend'] = vodIsend;
    data['vod_lock'] = vodLock;
    data['vod_level'] = vodLevel;
    data['vod_copyright'] = vodCopyright;
    data['vod_points'] = vodPoints;
    data['vod_points_play'] = vodPointsPlay;
    data['vod_points_down'] = vodPointsDown;
    data['vod_hits'] = vodHits;
    data['vod_hits_day'] = vodHitsDay;
    data['vod_hits_week'] = vodHitsWeek;
    data['vod_hits_month'] = vodHitsMonth;
    data['vod_duration'] = vodDuration;
    data['vod_up'] = vodUp;
    data['vod_down'] = vodDown;
    data['vod_score'] = vodScore;
    data['vod_score_all'] = vodScoreAll;
    data['vod_score_num'] = vodScoreNum;
    data['vod_time'] = vodTime;
    data['vod_time_add'] = vodTimeAdd;
    data['vod_time_hits'] = vodTimeHits;
    data['vod_time_make'] = vodTimeMake;
    data['vod_trysee'] = vodTrysee;
    data['vod_douban_id'] = vodDoubanId;
    data['vod_douban_score'] = vodDoubanScore;
    data['vod_reurl'] = vodReurl;
    data['vod_rel_vod'] = vodRelVod;
    data['vod_rel_art'] = vodRelArt;
    data['vod_pwd'] = vodPwd;
    data['vod_pwd_url'] = vodPwdUrl;
    data['vod_pwd_play'] = vodPwdPlay;
    data['vod_pwd_play_url'] = vodPwdPlayUrl;
    data['vod_pwd_down'] = vodPwdDown;
    data['vod_pwd_down_url'] = vodPwdDownUrl;
    data['vod_content'] = vodContent;
    data['vod_play_from'] = vodPlayFrom;
    data['vod_play_server'] = vodPlayServer;
    data['vod_play_note'] = vodPlayNote;
    data['vod_play_url'] = vodPlayUrl;
    data['vod_down_from'] = vodDownFrom;
    data['vod_down_server'] = vodDownServer;
    data['vod_down_note'] = vodDownNote;
    data['vod_down_url'] = vodDownUrl;
    data['vod_plot'] = vodPlot;
    data['vod_plot_name'] = vodPlotName;
    data['vod_plot_detail'] = vodPlotDetail;
    data['type_name'] = typeName;
    return data;
  }
}

class VideoSource {
  /*
{
  "code": 1,
  "msg": "数据列表",
  "page": 1,
  "pagecount": 4490,
  "limit": "20",
  "total": 89800,
  "list": [
    {
      "vod_id": 89394,
      "type_id": 6,
      "type_id_1": 1,
      "group_id": 0,
      "vod_name": "魔法坏女巫2",
      "vod_sub": "魔法坏女巫(下) / 魔法坏女巫：第二章(港) / 魔法坏女巫：第二部 / Wicked: Deuxième Partie / Wicked: Part Two‎",
      "vod_en": "mofahuainvwu2",
      "vod_status": 1,
      "vod_letter": "M",
      "vod_color": "",
      "vod_tag": "",
      "vod_class": "动作,爱情,歌舞,奇幻,冒险",
      "vod_pic": "https://img.ffzy888.com/upload/vod/20251119-1/f76c3bcd9e4834d48a80296c78c27d20.jpg",
      "vod_pic_thumb": "",
      "vod_pic_slide": "",
      "vod_pic_screenshot": "",
      "vod_actor": "辛西娅·埃里沃,爱莉安娜·格兰德,杰夫·高布伦,杨紫琼,乔纳森·贝利,伊桑·斯莱特,玛丽莎·博德,彼特·丁拉基,科尔曼·多明戈,亚当·詹姆斯,艾米丽·蒂尔尼,艾琳·巴特尔,迈克尔·瓜内拉,莎拉-杰恩·里德尔,雅雅·哈姆扎,瑞安·曼,乔尔·斯特恩,利里奥·博阿滕,莉兹·艾森,里卡多·卢德罗·苏萨,卡勒姆·鲍耶",
      "vod_director": "朱浩伟",
      "vod_writer": "莱曼·弗兰克·鲍姆,温妮·霍尔兹曼,格雷戈里·马奎尔",
      "vod_behind": "",
      "vod_blurb": "　　自从艾芙芭（辛西娅·埃里沃 饰）与格琳达（爱莉安娜·格兰德 饰）分道扬镳、形同陌路之后，各自承受她们做出的抉择所带来的后果。　　被冠上“西方坏女巫”恶名的艾芙芭遭到放逐后，隐居在奥兹国树林深处，但",
      "vod_remarks": "HD中字",
      "vod_pubdate": "2025-11-21",
      "vod_total": 0,
      "vod_serial": "",
      "vod_tv": "",
      "vod_weekday": "",
      "vod_area": "美国",
      "vod_lang": "英语",
      "vod_year": "2025",
      "vod_version": "",
      "vod_state": "正片",
      "vod_author": "",
      "vod_jumpurl": "",
      "vod_tpl": "",
      "vod_tpl_play": "",
      "vod_tpl_down": "",
      "vod_isend": 0,
      "vod_lock": 0,
      "vod_level": 0,
      "vod_copyright": 0,
      "vod_points": 0,
      "vod_points_play": 0,
      "vod_points_down": 0,
      "vod_hits": 0,
      "vod_hits_day": 0,
      "vod_hits_week": 0,
      "vod_hits_month": 0,
      "vod_duration": "",
      "vod_up": 0,
      "vod_down": 0,
      "vod_score": "0.0",
      "vod_score_all": 0,
      "vod_score_num": 0,
      "vod_time": "2025-12-30 14:59:31",
      "vod_time_add": 1763482690,
      "vod_time_hits": 0,
      "vod_time_make": 0,
      "vod_trysee": 0,
      "vod_douban_id": 36175206,
      "vod_douban_score": "0.0",
      "vod_reurl": "",
      "vod_rel_vod": "",
      "vod_rel_art": "",
      "vod_pwd": "",
      "vod_pwd_url": "",
      "vod_pwd_play": "",
      "vod_pwd_play_url": "",
      "vod_pwd_down": "",
      "vod_pwd_down_url": "",
      "vod_content": "<p>　　自从艾芙芭（辛西娅·埃里沃 饰）与格琳达（爱莉安娜·格兰德 饰）分道扬镳、形同陌路之后，各自承受她们做出的抉择所带来的后果。<br/>　　被冠上“西方坏女巫”恶名的艾芙芭遭到放逐后，隐居在奥兹国树林深处，但是却仍然为被噤声的动物争取自由而奋斗，并且迫切地想要揭露她所知道关于奥兹国大巫师（杰夫· 高布伦 饰）的真相。<br/>　　与此同时，格琳达已经成为奥兹国光鲜亮丽的良善象征，她住在翡翠城皇宫中， 享受她的响亮名声和超高人气所带来的明星光环与特权。在莫里贝尔夫人（杨紫琼 饰）的安排下，格琳达成为奥兹国人民眼中充满粉红泡泡的安抚力量，并且让他们相信奥兹国在大巫师的统治之下一切都很好。<br/>　　当格琳达的明星光环越来越闪亮，她也准备和费耶罗王子（乔纳森·贝利 饰）举行一场盛大的婚礼，但是她却一直受到她和艾芙芭分开后的阴影所纠缠。她试图促成艾芙芭与大巫师之间的和解，然而她所有的努力都以失败告终，使得艾芙芭和格琳达的关系越来越疏远。她们的关系决裂所造成的影响，将彻底改变博克（伊森·斯莱特 饰）与费耶罗的命运，也将威胁到艾芙芭的妹妹涅莎萝丝（玛丽莎·博德 饰）的安危，而一名来自堪萨斯州的少女也将闯入奥兹国，彻底翻转他们的世界。<br/>　　当一群愤怒的民众揭竿而起，打算对抗西方坏女巫，格琳达和艾芙芭就必须最后一次携手合作。当她们的友情成为改变她们未来的关键，她们就必须以真心诚意和无比的同理心真正了解彼此，并且改变自己，也让整个奥兹国变得更美好。</p>",
      "vod_play_from": "feifan$$$ffm3u8",
      "vod_play_server": "no$$$no",
      "vod_play_note": "$$$",
      "vod_play_url": "HD中字$https://vip.ffzy-online.com/share/7bda1a1c4b780f467d4ece9a47eb5c1b$$$HD中字$https://vip.ffzy-online.com/20251230/57466_7bda1a1c/index.m3u8",
      "vod_down_from": "",
      "vod_down_server": "",
      "vod_down_note": "",
      "vod_down_url": "",
      "vod_plot": 0,
      "vod_plot_name": "",
      "vod_plot_detail": "",
      "type_name": "动作片"
    }
  ]
} 
*/

  int? code;
  String? msg;
  int? pagecount;
  String? limit;
  int? total;
  List<VideoSourceListItem>? list;

  VideoSource({
    this.code,
    this.msg,
    this.pagecount,
    this.limit,
    this.total,
    this.list,
  });

  VideoSource.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    msg = json['msg']?.toString();
    pagecount = json['pagecount']?.toInt();
    limit = json['limit']?.toString();
    total = json['total']?.toInt();
    if (json['list'] != null) {
      final v = json['list'];
      final arr0 = <VideoSourceListItem>[];
      v.forEach((v) {
        arr0.add(VideoSourceListItem.fromJson(v));
      });
      list = arr0;
    }
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['msg'] = msg;
    data['pagecount'] = pagecount;
    data['limit'] = limit;
    data['total'] = total;
    if (list != null) {
      final v = list;
      final arr0 = [];
      for (var v in v!) {
        arr0.add(v.toJson());
      }
      data['list'] = arr0;
    }
    return data;
  }
}

class TiktokPagerItemInfo {
  final int vodId;
  final String vodName;
  final String vodPic;
  final String typeName;
  final String vodPlayNote;
  final String vodPlayUrl;
  final String vodPlayFrom;
  final String vodContent;

  TiktokPagerItemInfo({
    required this.vodId,
    required this.vodName,
    required this.vodPic,
    required this.typeName,
    required this.vodPlayNote,
    required this.vodPlayUrl,
    required this.vodPlayFrom,
    required this.vodContent,
  });
}
